[package]
name = "graphql_server"
version = "0.1.0"
authors = ["Klaus Purer <klaus.purer@protonmail.ch>"]
edition = "2018"

[dependencies]
futures = "0.1"
hyper = "0.12.35"
juniper = "0.14.1"
juniper_hyper = "0.5.1"
mysql = "17.0.0"
